# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: caterpiller
url: https://elemem.github.io
feed: /atom.xml
author_info: <a href="http://elemem.github.io/">elemem</a>

myblog:
  gavatar: images/2.jpg
  gpname: elemem
  github: https://github.com/elemem
  email: mailto:elemem08@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]

theme: jekyll-theme-hacker